version: "3.8"

services:
  web:
    build: ../web
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8000"       



        #  haproxy:
        #image: docker.io/library/haproxy:2.9
        #depends_on: [ web ]
        #ports: [ "0.0.0.0:8080:8080" ]
        #volumes:
        #- ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        #restart: unless-stopped

