services:
  web:
    build:
      context: ../web
    image: localhost/rncp-web:latest
    environment: [ APP_VERSION=v0.1.0 ]
    restart: unless-stopped
    expose:
      - "8000"
  haproxy:
    image: docker.io/library/haproxy:2.9
    depends_on: [ web ]
    ports: [ "0.0.0.0:8000:8080" ]
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped

