name: PR Env Down
on:
  pull_request:
    types: [closed]

jobs:
  down:
    runs-on: [self-hosted, proxmox, debian12]
    env:
      PROXMOX_VE_ENDPOINT: ${{ secrets.PROXMOX_VE_ENDPOINT }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      PROXMOX_VE_INSECURE: ${{ secrets.PROXMOX_VE_INSECURE }}
      VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      STACK_NAME: pr-${{ github.event.pull_request.number }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/setup-pulumi@v2
      - name: Destroy + remove stack
        run: |
          pulumi login --local
          pulumi stack select "$STACK_NAME"
          pulumi destroy -y
          pulumi stack rm -y "$STACK_NAME"
