name: PR Env Up (fail-first)
on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  up:
    runs-on: [self-hosted, proxmox, debian12]
    env:
      PROXMOX_VE_ENDPOINT: ${{ secrets.PROXMOX_VE_ENDPOINT }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}
      PROXMOX_VE_INSECURE: ${{ secrets.PROXMOX_VE_INSECURE }}
      VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      VM_SSH_PUBLIC_KEY: ${{ secrets.VM_SSH_PUBLIC_KEY }}
      STACK_NAME: pr-${{ github.event.pull_request.number }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/setup-pulumi@v2
      - name: Use system Python and prepare venv
        run: |
          # verify python3 presence
          python3 --version

          # create a reproducible venv named .venv (matches local dev)
          python3 -m venv .venv
          . .venv/bin/activate

          # upgrade pip and install deps
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Prepare Pulumi stack & config
        run: |
          source .venv/bin/activate
          pulumi login --local

          pulumi stack select --stack "$STACK_NAME" || pulumi stack init --stack "$STACK_NAME"
          pulumi config set --stack "$STACK_NAME" pulumi-py:pve:nodeName proxmox
          pulumi config set --stack "$STACK_NAME" pulumi-py:pve:datastoreId local-lvm
          pulumi config set --stack "$STACK_NAME" pulumi-py:pve:poolId ci-pool
          pulumi config set --stack "$STACK_NAME" pulumi-py:pve:templateVmid 9000
          pulumi config set --stack "$STACK_NAME" pulumi-py:vm:username debian
          #pulumi config set vm:bridge vmbr0
          # IP simple par PR (adapte le /24 si autre réseau)
          OCTET=$((150 + ${{ github.event.pull_request.number }} % 50))
          #pulumi config set vm:ipCidr "192.168.1.${OCTET}/24"
          #pulumi config set vm:gateway "192.168.1.1"
          pulumi config set --stack "$STACK_NAME" pulumi-py:vm:sshPubKey "${{ secrets.VM_SSH_PUBLIC_KEY }}"
          pulumi config set --stack "$STACK_NAME" pulumi-py:vm:cores     2
          pulumi config set --stack "$STACK_NAME" pulumi-py:vm:memoryMb  2048

      - name: pulumi up (expected to FAIL first)
        run: |
          source .venv/bin/activate
          pulumi up -y --non-interactive --stack "$STACK_NAME"
